version: '2'
services:
  web:
    image: dimilan/odoom
    depends_on:
      - db
    ports:
      - "80:80"
  db:
    image: dimilan/odoomdb
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
